# Generated by Django 3.1.6 on 2021-08-06 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restapi.constants

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=CATEGORY_MAX_LENGTH)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=EXPENSES_MAX_LENGTH)),
                ('total_amount', models.DecimalField(decimal_places=DECIMAL_PLACES, max_digits=MAX_DIGITS)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapi.category')),
            ],
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_owed', models.DecimalField(decimal_places=DECIMAL_PLACES, max_digits=MAX_DIGITS)),
                ('amount_lent', models.DecimalField(decimal_places=DECIMAL_PLACES, max_digits=MAX_DIGITS)),
                ('expense', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='restapi.expenses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=GROUPS_MAX_LENGTH)),
                ('members', models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expenses',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapi.groups'),
        ),
    ]
